### ISSUE TITLE
missing dependancy for ome_tiff_reader.py?

### ISSUE THREAD

**Issue by BioinfoTongLI** [haniffalab/sci-spatial-data#1]
Hi @davehorsfall,
I think there's one missing dep file [here](https://github.com/haniffalab/sci-spatial-data/blob/main/python/ome_tiff_reader.py#L14).

Is it [this one](https://github.com/vitessce/vitessce-data/blob/master/python/tile_zarr_base.py) from vitessce?

**Comment by davehorsfall** [comment]
Thanks @BioinfoTongLI, I had accidentally dropped that file in the init commit because it was commented out. I've only just picked this issue up, but the `tile_zarr_base` helper file was added yesterday in fd67cd4131841c22a557527f4e8c0f692e3ba7db.
