### ISSUE TITLE
Is missing cells in either label image or h5ad file an issue for interactive visualization?

### ISSUE THREAD

**Issue by BioinfoTongLI** [haniffalab/sci-spatial-data#19]
It is possible that not all cells in the label image will be kept after sc analysis.
We need to find out whether those missing cells in the h5ad will freeze the GUI/make other widgets unusable.

**Comment by BioinfoTongLI** [comment]
@dannda thanks! I see.
so, it's basically just a visualization issue?
Is there any mismatching between widgets?

If it's just a color coding issue, users can specify color range in the `spatial` widget you're showing here, no?

**Comment by dannda** [comment]
Yes, it's only a visualization issue. There is no mismatch between widgets.

Users can specify the colormap and range but from what I've been testing the extra cells would still get the lower end of the color range. Looking at the code it seems like the cells are supposed to get a default gray color like when the spatial data is loaded without any gene selections (like the first screenshot on my previous comment), but it is not working in this case. The default gray color also works when making manual selections in the spatial or scatterplot components, so it might just be a bug with gene selection.

**Comment by BioinfoTongLI** [comment]
thanks @dannda ! I will then prepare a label image with only one-to-one mapped cells.

I'll leave this open once we've had all checked before the milestone.

**Comment by BioinfoTongLI** [comment]
all seems to be running fine with filtered sc data from both ISS and Visium. Closing this
