### ISSUE TITLE
Modify config build to check for list of jsons

### ISSUE THREAD

**Issue by davehorsfall** [haniffalab/sci-spatial-data#6]

**Comment by davehorsfall** [comment]
We need to modify the `write_raster_json` function in `build_config.py` so that it checks for the existence of json files and inserts them into the config if they do exist.

**Comment by dannda** [comment]
Modified the build_config.py to check for JSON files that follow [Vitessce’s file types](http://vitessce.io/docs/data-types-file-types/) within the `params.outdir`
#9

**Comment by davehorsfall** [comment]
Complete
